name: Auto Update Series Playlist

on:
  schedule:
    # Menjalankan script otomatis setiap 2 jam sekali
    - cron: '0 */2 * * *'
  workflow_dispatch: # Tombol eksekusi manual via tab Actions

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script
        run: python generate_m3u.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add playlist-vidio.m3u
          git commit -m "Auto-update series playlist $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
