name: Auto Update M3U Playlists

on:
  schedule:
    # Menjalankan script setiap 3 jam sekali
    - cron: '0 */3 * * *'
  workflow_dispatch: # Mengizinkan eksekusi manual via tombol "Run workflow"

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Mengizinkan bot untuk menyimpan file ke repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Script Utama (Master, Series, Movie)
        run: python generate_m3u.py

      - name: Run Script Khusus (Live Only)
        run: python generate_live.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Baris ini akan otomatis mendeteksi dan menyimpan SEMUA file (.m3u)
          # Termasuk file live_only.m3u yang baru
          git add *.m3u
          
          # Menyimpan dengan pesan commit berisi tanggal & jam saat ini
          git commit -m "Auto-update all playlists $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
